###
POST http://127.0.0.1:3000/anime/create-one-anime HTTP/1.1
Content-Type: application/json

{
   "uid": 281339680,
   "title": "Adventure Quest",
   "synopsis": "Join our heroes on an epic quest through magical lands and treacherous dungeons.",
   "genre": "Adventure, Fantasy",
   "aired": "Fall 2023",
   "episodes": 24,
   "members": 8000,
   "popularity": 1500,
   "ranked": 30,
   "score": 9.0,
   "img_url": "https://example.com/adventure-quest-image.jpg",
   "link": "https://example.com/adventure-quest"
}
###
POST http://127.0.0.1:3000/anime/delete-one-anime-by-uid HTTP/1.1
Content-Type: application/json

{
    "uid": 281049682
}

###
POST http://127.0.0.1:3000/anime/delete-many-anime-by-uid HTTP/1.1
Content-Type: application/json

{
    "uid": [281049680,281049681,281049682]
}

###
POST  http://127.0.0.1:3000/anime/update-one-anime HTTP/1.1
Content-Type: application/json

{
    "uid": 281049679,
    "title": "Sabeh Anime"
}


###
GET http://127.0.0.1:3000/anime/read-one-anime HTTP/1.1
Content-Type: application/json

{
    "uid": 281339680
}

###
GET http://127.0.0.1:3000/anime/read-many-anime HTTP/1.1
Content-Type: application/json

{
    "uid": [281049680,281049681]
}








